### ISSUE TITLE
How  can  i  save the  no_top.h5  of  MobileNet_v2  which  trained in my own datasets ?

### ISSUE THREAD

**Issue by Zhangxiaof001** [JonathanCMitchell/mobilenet_v2_keras#9]
Excuse me  ,how  can  i  save the  no_top.h5  of  MobileNet_v2  which  trained in my own datasets ?

**Comment by JonathanCMitchell** [comment]
Just save it using Keras standard save model functions

**Comment by Zhangxiaof001** [comment]
@JonathanCMitchell Thank you very much .
